apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: chatbot
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: url-shortener
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    type: Container
