apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: taskapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/data/taskapp/postgres
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/data/taskapp/postgres
      property: password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: secret/data/taskapp/postgres
      property: database
