apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-frontend
  namespace: taskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapp-frontend
  template:
    metadata:
      labels:
        app: taskapp-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      initContainers:
      - name: setup
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /html
            cat > /html/index.html << 'ENDHTML'
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>TaskApp - Full-Stack Demo</title>
                <style>
                    * { margin: 0; padding: 0; box-sizing: border-box; }
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        min-height: 100vh;
                        padding: 20px;
                    }
                    .container {
                        max-width: 800px;
                        margin: 0 auto;
                        background: white;
                        border-radius: 20px;
                        box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                        padding: 40px;
                    }
                    h1 {
                        color: #667eea;
                        margin-bottom: 10px;
                        font-size: 2.5em;
                    }
                    .subtitle {
                        color: #666;
                        margin-bottom: 30px;
                        font-size: 1.1em;
                    }
                    .tech-stack {
                        background: #f8f9fa;
                        padding: 15px;
                        border-radius: 10px;
                        margin-bottom: 30px;
                        font-size: 0.9em;
                        color: #666;
                    }
                    .input-group {
                        display: flex;
                        gap: 10px;
                        margin-bottom: 20px;
                    }
                    input[type="text"] {
                        flex: 1;
                        padding: 15px;
                        border: 2px solid #e0e0e0;
                        border-radius: 10px;
                        font-size: 1em;
                        transition: border 0.3s;
                    }
                    input[type="text"]:focus {
                        outline: none;
                        border-color: #667eea;
                    }
                    button {
                        padding: 15px 30px;
                        background: #667eea;
                        color: white;
                        border: none;
                        border-radius: 10px;
                        font-size: 1em;
                        cursor: pointer;
                        transition: background 0.3s;
                    }
                    button:hover {
                        background: #5568d3;
                    }
                    .task-list {
                        list-style: none;
                    }
                    .task-item {
                        background: #f8f9fa;
                        padding: 15px;
                        margin-bottom: 10px;
                        border-radius: 10px;
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                        transition: all 0.3s;
                    }
                    .task-item:hover {
                        background: #e9ecef;
                        transform: translateX(5px);
                    }
                    .task-item.completed {
                        opacity: 0.6;
                        text-decoration: line-through;
                    }
                    .task-actions {
                        display: flex;
                        gap: 10px;
                    }
                    .task-actions button {
                        padding: 8px 15px;
                        font-size: 0.9em;
                    }
                    .delete-btn {
                        background: #dc3545;
                    }
                    .delete-btn:hover {
                        background: #c82333;
                    }
                    .complete-btn {
                        background: #28a745;
                    }
                    .complete-btn:hover {
                        background: #218838;
                    }
                    .loading {
                        text-align: center;
                        color: #667eea;
                        padding: 20px;
                    }
                    .stats {
                        margin-top: 20px;
                        padding: 15px;
                        background: #e7f3ff;
                        border-radius: 10px;
                        color: #004085;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>🚀 TaskApp</h1>
                    <p class="subtitle">Full-Stack Kubernetes Demo - CI/CD Deployed! ✅</p>
                    <div class="tech-stack">
                        <strong>Tech Stack:</strong> React Frontend • Node.js/Express API • PostgreSQL Database • Kubernetes • cert-manager TLS
                    </div>
                    
                    <div class="input-group">
                        <input type="text" id="taskInput" placeholder="Enter a new task..." />
                        <button onclick="addTask()">Add Task</button>
                    </div>
                    
                    <div id="loading" class="loading" style="display:none;">Loading tasks...</div>
                    <ul id="taskList" class="task-list"></ul>
                    
                    <div class="stats" id="stats"></div>
                </div>
                
                <script>
                    const API_URL = '/api';
                    
                    async function loadTasks() {
                        document.getElementById('loading').style.display = 'block';
                        try {
                            const response = await fetch(`${API_URL}/tasks`);
                            const tasks = await response.json();
                            displayTasks(tasks);
                            updateStats(tasks);
                        } catch (error) {
                            console.error('Error loading tasks:', error);
                            alert('Failed to load tasks. Check console for details.');
                        }
                        document.getElementById('loading').style.display = 'none';
                    }
                    
                    function displayTasks(tasks) {
                        const taskList = document.getElementById('taskList');
                        taskList.innerHTML = '';
                        tasks.forEach(task => {
                            const li = document.createElement('li');
                            li.className = `task-item ${task.completed ? 'completed' : ''}`;
                            li.innerHTML = `
                                <span>${task.title}</span>
                                <div class="task-actions">
                                    <button class="complete-btn" onclick="toggleTask(${task.id}, ${!task.completed})">
                                        ${task.completed ? 'Undo' : 'Complete'}
                                    </button>
                                    <button class="delete-btn" onclick="deleteTask(${task.id})">Delete</button>
                                </div>
                            `;
                            taskList.appendChild(li);
                        });
                    }
                    
                    async function addTask() {
                        const input = document.getElementById('taskInput');
                        const title = input.value.trim();
                        if (!title) return;
                        
                        try {
                            await fetch(`${API_URL}/tasks`, {
                                method: 'POST',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({ title })
                            });
                            input.value = '';
                            loadTasks();
                        } catch (error) {
                            console.error('Error adding task:', error);
                            alert('Failed to add task');
                        }
                    }
                    
                    async function toggleTask(id, completed) {
                        try {
                            await fetch(`${API_URL}/tasks/${id}`, {
                                method: 'PUT',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({ completed })
                            });
                            loadTasks();
                        } catch (error) {
                            console.error('Error updating task:', error);
                        }
                    }
                    
                    async function deleteTask(id) {
                        if (!confirm('Delete this task?')) return;
                        try {
                            await fetch(`${API_URL}/tasks/${id}`, { method: 'DELETE' });
                            loadTasks();
                        } catch (error) {
                            console.error('Error deleting task:', error);
                        }
                    }
                    
                    function updateStats(tasks) {
                        const total = tasks.length;
                        const completed = tasks.filter(t => t.completed).length;
                        const pending = total - completed;
                        document.getElementById('stats').innerHTML = `
                            <strong>Statistics:</strong> ${total} total tasks | ${completed} completed | ${pending} pending
                        `;
                    }
                    
                    // Allow Enter key to add task
                    document.getElementById('taskInput').addEventListener('keypress', (e) => {
                        if (e.key === 'Enter') addTask();
                    });
                    
                    // Load tasks on page load
                    loadTasks();
                </script>
            </body>
            </html>
            ENDHTML
        volumeMounts:
        - name: html
          mountPath: /html
      volumes:
      - name: html
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: taskapp
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://taskapp-backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp-frontend
  namespace: taskapp
spec:
  selector:
    app: taskapp-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
