apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskapp-backend-pdb
  namespace: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: taskapp-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskapp-frontend-pdb
  namespace: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: taskapp-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
