apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskapp
type: Opaque
stringData:
  POSTGRES_USER: taskapp
  POSTGRES_PASSWORD: CHANGE_ME_IN_PRODUCTION
  POSTGRES_DB: taskappdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskapp
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
