apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskapp
type: Opaque
stringData:
  POSTGRES_USER: taskapp
  POSTGRES_PASSWORD: CHANGE_ME_IN_PRODUCTION
  POSTGRES_DB: taskappdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: taskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClass: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskapp
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
