apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: taskapp
  labels:
    app.kubernetes.io/name: postgres-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: postgres-backup
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/taskapp-role"
            vault.hashicorp.com/agent-inject-template-db-creds: |
              {{- with secret "database/creds/taskapp-role" -}}
              export DATABASE_USER="{{ .Data.username }}"
              export DATABASE_PASSWORD="{{ .Data.password }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-vault-addr: "http://vault.vault.svc.cluster.local:8200"
            vault.hashicorp.com/role: "taskapp-role"
        spec:
          serviceAccountName: default
          securityContext:
            runAsNonRoot: true
            runAsUser: 70
          containers:
          - name: backup
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              . /vault/secrets/db-creds
              PGPASSWORD="$DATABASE_PASSWORD" pg_dump -h postgres -U "$DATABASE_USER" taskappdb > /backup/taskapp-$(date +%Y%m%d).sql
              echo "Backup completed: $(wc -c < /backup/taskapp-$(date +%Y%m%d).sql) bytes"
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            emptyDir: {}
