apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: platform-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "{{ .database }}"
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@postgres:5432/{{ .database }}"
  data:
  - secretKey: username
    remoteRef:
      key: secret/data/platform-store/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/platform-store/postgres
      property: password
  - secretKey: database
    remoteRef:
      key: secret/data/platform-store/postgres
      property: database
