apiVersion: v1
kind: ConfigMap
metadata:
  name: api-python-script
  namespace: dashboard
data:
  app.py: |
    from flask import Flask, jsonify
    from kubernetes import client, config
    import os

    app = Flask(__name__)

    # Load in-cluster config (uses the ServiceAccount token)
    config.load_incluster_config()
    v1 = client.CoreV1Api()

    @app.route('/api/pods')
    def get_pods():
        try:
            pods = v1.list_pod_for_all_namespaces(watch=False)
            pod_list = []
            for pod in pods.items:
                pod_list.append({
                    "name": pod.metadata.name,
                    "namespace": pod.metadata.namespace,
                    "status": pod.status.phase
                })
            return jsonify(pod_list)
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000)
