apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Newbigfonsz/platform-engineering-lab.git
    targetRevision: main
    path: apps/code-server
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
