apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: "1"
                memory: 2Gi
            containers:
              - name: prometheus
                startupProbe:
                  httpGet:
                    path: /-/ready
                    port: http-web
                    scheme: HTTP
                  failureThreshold: 300
                  periodSeconds: 5
                  timeoutSeconds: 3
        grafana:
          adminPassword: ${GRAFANA_ADMIN_PASSWORD}
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.alphonzojonesjr.com
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
              - hosts:
                  - grafana.alphonzojonesjr.com
                secretName: grafana-tls
          additionalDataSources:
            - name: Tempo
              type: tempo
              url: http://tempo.monitoring.svc:3100
              access: proxy
              jsonData:
                tracesToMetrics:
                  datasourceUid: prometheus
                serviceMap:
                  datasourceUid: prometheus
                nodeGraph:
                  enabled: true
                tracesToLogs:
                  datasourceUid: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
