apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      values: |
        grafana:
          adminPassword: ${GRAFANA_ADMIN_PASSWORD}
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.alphonzojonesjr.com
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
