apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.73.1
    helm:
      values: |
        mode: deployment
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          processors:
            batch:
              timeout: 5s
              send_batch_size: 1024
            memory_limiter:
              check_interval: 1s
              limit_mib: 400
              spike_limit_mib: 100
          exporters:
            otlp/tempo:
              endpoint: tempo.monitoring.svc:4317
              tls:
                insecure: true
            prometheus:
              endpoint: 0.0.0.0:8889
              namespace: otel
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/tempo]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [prometheus]
        ports:
          otlp:
            enabled: true
            containerPort: 4317
            servicePort: 4317
            protocol: TCP
          otlp-http:
            enabled: true
            containerPort: 4318
            servicePort: 4318
            protocol: TCP
          metrics:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            protocol: TCP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
