apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Newbigfonsz/platform-engineering-lab.git
    targetRevision: main
    path: apps/platform-store
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
