---
# Default deny all ingress and egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
# Allow API server to reach vault-agent-injector webhook
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: vault
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP

---
# Allow vault clients from any namespace on ports 8200/8201
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vault-clients
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8200
          protocol: TCP
        - port: 8201
          protocol: TCP

---
# Allow external-secrets to reach vault on 8200
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-secrets
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: external-secrets
      ports:
        - port: 8200
          protocol: TCP

---
# Allow ingress-nginx to reach vault UI on 8200
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8200
          protocol: TCP

---
# Allow kube-api / node network to reach vault on 8200/8201
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-api
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.10.0.0/24
      ports:
        - port: 8200
          protocol: TCP
        - port: 8201
          protocol: TCP

---
# Allow monitoring namespace to scrape metrics
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring

---
# Allow DNS egress for all vault pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
# Allow vault egress: raft replication, K8s API, TLS, and Postgres dynamic creds
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vault-egress
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Raft replication between vault pods
    - to:
        - podSelector: {}
      ports:
        - port: 8200
          protocol: TCP
        - port: 8201
          protocol: TCP
    # K8s API and TLS
    - ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
    # Dynamic database credentials — Vault connects to Postgres in taskapp
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: taskapp
      ports:
        - port: 5432
          protocol: TCP
